title: ECLOGUE PRESS
url: https://waypointinstitute.github.io
baseurl: /eclogue

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  team:
    output: false
  books:
    output: true
    permalink: /books/:name/
